# Generated by Django 3.1.2 on 2020-11-13 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('customer_service', '0002_auto_20201113_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='total',
            field=models.FloatField(default=0, verbose_name='Total'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.service')),
            ],
        ),
        migrations.AddField(
            model_name='customerservice',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='customer_service.serviceitem'),
            preserve_default=False,
        ),
    ]
