# Generated by Django 3.1.2 on 2020-11-14 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0003_auto_20201113_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerservice',
            name='service',
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='customerservice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='customer_service.customerservice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
