# Generated by Django 3.1.2 on 2020-11-14 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('customers', '0015_auto_20201112_1109'),
        ('customer_service', '0004_auto_20201113_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='customerservice',
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service'),
        ),
    ]
