# Generated by Django 3.1.2 on 2020-11-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0006_customerservice_serviceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='customer',
        ),
    ]
