# Generated by Django 3.1.2 on 2020-11-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0009_serviceitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='price',
        ),
    ]
