# Generated by Django 3.1.2 on 2020-11-16 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_auto_20201112_1109'),
        ('customer_service', '0011_auto_20201114_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='discount',
            field=models.CharField(blank=True, choices=[('5', '5%'), ('10', '10%'), ('15', '15%'), ('20', '20%')], max_length=2, verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='start',
            field=models.TimeField(verbose_name='Hora de início'),
        ),
    ]
