# Generated by Django 3.1.2 on 2020-11-16 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_auto_20201112_1109'),
        ('customer_service', '0012_auto_20201116_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerservice',
            name='serviceitem',
        ),
        migrations.AddField(
            model_name='customerservice',
            name='service_item',
            field=models.ManyToManyField(related_name='customeritem', through='customer_service.ServiceItem', to='customers.Customer'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='customerservice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='customer_service.customerservice'),
        ),
    ]
