# Generated by Django 3.1.2 on 2020-11-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0015_auto_20201116_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='payment',
            field=models.CharField(choices=[('0', 'À vista'), ('0.0239', 'Débito'), ('0.0525', '1x'), ('0.11', '2x'), ('0.1273', '3x')], max_length=20, verbose_name='Pagamento'),
        ),
    ]
