# Generated by Django 3.1.2 on 2020-11-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0016_auto_20201116_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='serviceitem',
            field=models.ManyToManyField(related_name='serviceitem', to='customer_service.ServiceItem'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='customerservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customerservice', to='customer_service.customerservice'),
        ),
    ]
