# Generated by Django 3.1.2 on 2020-11-16 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_auto_20201112_1109'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_service', '0019_auto_20201116_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
