# Generated by Django 3.1.2 on 2020-11-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0020_auto_20201116_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='serviceitem',
            field=models.ManyToManyField(related_name='serviceitem', to='customer_service.ServiceItem'),
        ),
    ]
