# Generated by Django 3.1.2 on 2020-11-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0021_customerservice_serviceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerservice',
            name='serviceitem',
        ),
    ]
