# Generated by Django 3.1.2 on 2020-11-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0022_remove_customerservice_serviceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='total',
            field=models.CharField(default='', max_length=20, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
