# Generated by Django 3.1.2 on 2020-11-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0023_customerservice_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='total',
            field=models.CharField(blank=True, max_length=20, verbose_name='Total'),
        ),
    ]
