# Generated by Django 3.1.2 on 2020-11-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0024_auto_20201117_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerservice',
            name='total',
        ),
        migrations.AddField(
            model_name='customerservice',
            name='finish',
            field=models.TimeField(auto_now=True, verbose_name='Hora de Término'),
        ),
    ]
