# Generated by Django 3.1.2 on 2020-11-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0025_auto_20201117_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='finish',
            field=models.TimeField(verbose_name='Hora de Término'),
        ),
    ]
