# Generated by Django 3.1.2 on 2020-11-18 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0026_auto_20201117_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerservice',
            name='finish',
        ),
    ]
