# Generated by Django 3.1.2 on 2020-11-18 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0028_auto_20201118_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Atendido em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerservice',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
    ]
