# Generated by Django 3.1.2 on 2020-11-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0029_auto_20201118_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerservice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customerservice',
            name='modified_at',
        ),
    ]
