# Generated by Django 3.1.2 on 2020-11-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('customer_service', '0030_auto_20201118_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='customerservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerservice', to='customer_service.customerservice'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
