# Generated by Django 3.1.2 on 2020-11-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0032_auto_20201119_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
