# Generated by Django 3.1.2 on 2020-12-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0034_auto_20201204_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
