# Generated by Django 3.1.2 on 2020-12-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0036_auto_20201207_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='comission',
            field=models.PositiveIntegerField(default=100, verbose_name='Comissão (%)'),
        ),
    ]
