# Generated by Django 3.1.2 on 2020-12-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='Item')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('type', models.CharField(choices=[('u', 'Unitário'), ('f', 'Fracionado')], max_length=1, verbose_name='Tipo')),
            ],
        ),
    ]
