# Generated by Django 3.1.2 on 2020-12-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20201209_1644'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='StockItem',
        ),
    ]
