# Generated by Django 3.1.2 on 2021-01-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='stock_item',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
