# Generated by Django 3.1.2 on 2021-01-08 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20210108_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kit',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_item', to='stock.stock'),
        ),
    ]
