# Generated by Django 3.1.2 on 2021-01-08 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_remove_kit_stock_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='kit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit', to='stock.kit'),
        ),
    ]
