# Generated by Django 3.1.2 on 2021-01-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_stock_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
