# Generated by Django 3.1.2 on 2021-01-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_kit_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='kit',
        ),
        migrations.AddField(
            model_name='kit',
            name='items',
            field=models.ManyToManyField(to='stock.Stock'),
        ),
    ]
