# Generated by Django 3.1.2 on 2021-01-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_auto_20210108_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kititem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='kit',
        ),
        migrations.DeleteModel(
            name='Kit',
        ),
        migrations.DeleteModel(
            name='KitItem',
        ),
    ]
