# Generated by Django 3.1.2 on 2020-11-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255, verbose_name='Serviço')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('duration', models.DurationField(verbose_name='Duração')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Custo')),
            ],
        ),
    ]
