# Generated by Django 3.1.2 on 2020-12-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='comission',
            field=models.IntegerField(default=0, verbose_name='Comissão'),
            preserve_default=False,
        ),
    ]
