# Generated by Django 3.1.2 on 2020-12-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_comission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='comission',
        ),
    ]
