# Generated by Django 3.1.2 on 2020-12-08 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_comission'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='Item')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kititem', to='services.service')),
            ],
        ),
    ]
