# Generated by Django 3.1.2 on 2020-12-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20201209_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kititem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
