# Generated by Django 3.1.2 on 2020-12-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20201209_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kititem',
            old_name='service',
            new_name='serviceki',
        ),
    ]
