# Generated by Django 3.1.2 on 2020-12-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20201209_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kititem',
            old_name='serviceki',
            new_name='service',
        ),
        migrations.AddField(
            model_name='kititem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kititem',
            name='item',
            field=models.CharField(max_length=255, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='kititem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
    ]
