# Generated by Django 3.1.2 on 2020-12-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20201209_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kititem',
            name='price',
        ),
    ]
