# Generated by Django 3.1.2 on 2020-12-09 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('services', '0013_remove_kititem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kititem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockitem', to='stock.stock'),
        ),
    ]
