# Generated by Django 3.1.2 on 2020-12-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20201209_1658'),
        ('services', '0015_auto_20201209_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kititem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_stock', to='stock.stock'),
        ),
    ]
