# Generated by Django 3.1.2 on 2021-01-08 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0003_remove_kit_kititem'),
        ('services', '0016_auto_20201211_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kititem', to='kit.kit')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitservice', to='services.service')),
            ],
        ),
        migrations.DeleteModel(
            name='KitItem',
        ),
    ]
