# Generated by Django 3.1.2 on 2021-01-08 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20210108_1617'),
        ('kit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kititem',
            name='kit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit', to='kit.kit'),
        ),
        migrations.AlterField(
            model_name='kititem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kititem', to='stock.stock'),
        ),
    ]
