# Generated by Django 3.1.2 on 2020-11-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('sex', models.CharField(max_length=10, verbose_name='Sexo')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('district', models.CharField(max_length=255, verbose_name='Bairro')),
                ('birth', models.DateField(max_length=10, verbose_name='Data de nascimento')),
            ],
        ),
    ]
