# Generated by Django 3.1.2 on 2020-11-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20201103_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth',
            field=models.DateField(blank=True, max_length=10, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bairro'),
        ),
    ]
