# Generated by Django 3.1.2 on 2020-11-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20201103_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth',
            field=models.DateField(max_length=10, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(max_length=255, verbose_name='Bairro'),
        ),
    ]
