# Generated by Django 3.1.2 on 2020-11-06 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20201106_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='modified_at',
            field=models.DateField(auto_now=True, verbose_name='Modificado em'),
        ),
    ]
