# Generated by Django 3.1.2 on 2020-11-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_customer_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to='pictures/%Y/%m/', verbose_name='Foto'),
        ),
    ]
