# Generated by Django 3.1.2 on 2020-11-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_auto_20201107_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='uid',
        ),
    ]
