# Generated by Django 3.1.2 on 2020-11-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_auto_20201107_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='uid',
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
