# Generated by Django 3.1.2 on 2020-11-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_auto_20201111_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='new_id',
        ),
    ]
