# Generated by Django 3.1.2 on 2020-11-11 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_remove_customer_new_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
