# Generated by Django 3.1.2 on 2020-11-11 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_auto_20201111_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='new_id',
            field=models.UUIDField(default=uuid.UUID('1dd54000-2455-11eb-89a5-3cf8f3c93101'), editable=False, unique=True),
        ),
    ]
