# Generated by Django 3.1.2 on 2020-11-11 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0025_auto_20201111_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
